### ISSUE TITLE
Concurrency checks are not validating subresources accesses correctly

### ISSUE THREAD

**Issue by Cyphall** [GPUOpen-Tools/GPU-Reshape#57]
Follow-up of the second issue reported in [this message](https://github.com/GPUOpen-Tools/GPU-Reshape/issues/49#issuecomment-1913604295) in issue #49.

> I am getting a few "Potential race condition detected" between [this write](https://github.com/Cyphall/Cyph3D/blob/98cacba4d565beaf5ddb39ad80c26fdec90eaf00/resources/shaders/internal/asset%20processing/gen%20cubemap.comp#L52) in the "cubemap generation" step and [this read](https://github.com/Cyphall/Cyph3D/blob/98cacba4d565beaf5ddb39ad80c26fdec90eaf00/resources/shaders/internal/asset%20processing/gen%20mipmap.comp#L31) in the "mipmaps generation" step when processing an equirectangular skybox.
> I _think_ the synchronization is good but maybe I'm wrong?

Initial diagnostic:

> Currently, concurrency doesn't track at a per-subresource level. So it incorrectly marks it as a race condition.

**Comment by miguel-petersen** [comment]
Just making note that I'll try addressing it this month.

**Comment by miguel-petersen** [comment]
The development branch now features "Texel Addressing", which enables per-texel (textures) and per-byte (buffers) tracking for initialization and concurrency validation. Quite a lot of changes went in for that!

It'll be part of an upcoming release quite soon. 🙂

**Comment by miguel-petersen** [comment]
Heya, Beta2 now includes all relevant changes for concurrency validation on a per-texel level.

**Comment by miguel-petersen** [comment]
I'll close this issue for now, in case you run into a similar issue, or believe something to be faulty, feel free to re-open this issue.
