### ISSUE TITLE
Overflow of register mapping leads to crash 

### ISSUE THREAD

**Issue by gaida-exe** [GPUOpen-Tools/GPU-Reshape#60]
I encountered a crash with setting the ShaderRegister of a D3D12_STATIC_SAMPLER_DESC to UINT32_MAX.
This leads to an overflow in the uint32_t offset and results to a resize of 0.
```
    // Ensure mappings length
    if (userSpace.mappings.size() <= offset) {
        userSpace.mappings.resize(offset + 1);
    }
```
A simple cast to size_t would do the job or a check for UINT32_MAX.
[Source\Backends\DX12\Layer\Source\RootSignature.cpp#L157](https://github.com/GPUOpen-Tools/GPU-Reshape/blob/main/Source/Backends/DX12/Layer/Source/RootSignature.cpp#L157)

**Comment by miguel-petersen** [comment]
Hi @gaida-exe,

There's been a couple of fixes in the development branch regarding unbounded stuff, however, that doesn't seem to be the case here?

What is the expected behaviour with setting the ShaderRegister of a static sampler to UINT32_MAX? I haven't encountered this before, and I don't see it mentioned in msdn.

**Comment by gaida-exe** [comment]
Hi @miguel-petersen,
UINT32_MAX is an internal special case for a default sampler, it is just a valid register and nothing special from the DX12 perspective.

**Comment by miguel-petersen** [comment]
I see, I've been banking on that the registers are stored somewhat sequentially, and hopefully contiguously, from 0. This of course goes against that (an oversight on my part).

The solution is likely to have the lookup be a map or something. I need a little bit of time to implement this.

**Comment by gaida-exe** [comment]
Thanks @miguel-petersen ! We have changed the code on our side already, but maybe others would also encounter this.

**Comment by miguel-petersen** [comment]
Ah appreciate it @gaida-exe.

And indeed, if the spec allows for something, we have to support it. 🙂

**Comment by miguel-petersen** [comment]
Hi @gaida-exe , a fix has been submitted to the development branch. Seems stable on a bunch of titles.

**Comment by gaida-exe** [comment]
Hi @miguel-petersen, I will give it a try on Monday. Thanks for the fix!

**Comment by gaida-exe** [comment]
Hi @miguel-petersen, I checked it out and it fixes the Problem!
